// components/SettingsPage.jsx
'use client';
import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { 
  User, Palette, Type, FileText, Save, 
  Monitor, Sun, Moon, Download, 
  Settings as SettingsIcon, ArrowLeft,
  Check, X, Mail, AlertCircle
} from 'lucide-react';
import SettingsCard from './SettingsCard';
import Toggle from './Toggle';
import Button from './Button';
import ColorPicker from './ColorPicker';
import Slider from './Slider';
import Select from './Select';
import { useTheme } from '../lib/theme-context';
import { emailService } from '../lib/email-service';
import { exportService } from '../lib/export-service';

const SettingsPage = () => {
  const router = useRouter(); // Add this line
  const { theme, toggleTheme } = useTheme();
  const isDark = theme === 'dark';
  
  const [settings, setSettings] = useState({
    profile: {
      name: 'John Doe',
      avatarColor: '#6366f1'
    },
    theme: {
      mode: theme
    },
    editor: {
      fontSize: 16,
      lineHeight: 1.6,
      fontFamily: 'Inter'
    },
    export: {
      defaultFormat: 'markdown',
      includeMetadata: true
    }
  });

  const [hasChanges, setHasChanges] = useState(false);
  const [showSaveNotification, setShowSaveNotification] = useState(false);
  const [exportStatus, setExportStatus] = useState({
    isExporting: false,
    message: '',
    error: ''
  });

  const [emailStatus, setEmailStatus] = useState({
    isSending: false,
    message: '',
    error: ''
  });

  useEffect(() => {
    setSettings(prev => ({
      ...prev,
      theme: { mode: theme }
    }));
  }, [theme]);

  const updateSetting = (section, key, value) => {
    setSettings(prev => ({
      ...prev,
      [section]: {
        ...prev[section],
        [key]: value
      }
    }));
    setHasChanges(true);
  };

  const handleSave = () => {
    // Simulate save operation
    setTimeout(() => {
      setHasChanges(false);
      setShowSaveNotification(true);
      setTimeout(() => setShowSaveNotification(false), 3000);
    }, 500);
  };

  // Add this function to handle back navigation
  const handleGoBack = () => {
    router.push('/'); // Navigate to home page
    // Alternative: router.back(); // Go to previous page
  };

  // Functional export handler
  const handleExport = async (format) => {
    setExportStatus({ isExporting: true, message: '', error: '' });
    
    try {
      const sampleContent = `# Sample Document Export
      
This is a sample document exported from CollaboDoc.

## Features
- Real-time collaboration
- Version history
- Advanced settings
- Multiple export formats

## Export Details
- Format: ${format.toUpperCase()}
- Date: ${new Date().toLocaleDateString()}
- Time: ${new Date().toLocaleTimeString()}

Generated by CollaboDoc - The ultimate collaborative document editor.`;

      await exportService.exportDocument({
        format: format,
        content: sampleContent,
        filename: `collabodoc-export-${Date.now()}.${format}`
      });

      setExportStatus({
        isExporting: false,
        message: `Successfully exported as ${format.toUpperCase()}`,
        error: ''
      });

      // Clear success message after 3 seconds
      setTimeout(() => {
        setExportStatus(prev => ({ ...prev, message: '' }));
      }, 3000);

    } catch (error) {
      setExportStatus({
        isExporting: false,
        message: '',
        error: `Export failed: ${error.message}`
      });
    }
  };

  // Functional email handler
  const handleSendEmail = async (type) => {
    setEmailStatus({ isSending: true, message: '', error: '' });
    
    try {
      let success = false;
      
      switch (type) {
        case 'password-reset':
          success = await emailService.sendPasswordResetEmail(
            'user@example.com',
            'reset-token-' + Date.now()
          );
          break;
        case 'account-update':
          success = await emailService.sendAccountUpdateEmail(
            'user@example.com',
            'Updated'
          );
          break;
        case 'data-export':
          success = await emailService.sendDataExportEmail(
            'user@example.com',
            {
              format: 'pdf',
              content: 'Sample export content',
              filename: 'export.pdf'
            }
          );
          break;
        default:
          throw new Error('Unknown email type');
      }

      if (success) {
        setEmailStatus({
          isSending: false,
          message: `Email sent successfully for ${type}`,
          error: ''
        });
      } else {
        throw new Error('Email service returned false');
      }

      // Clear success message after 3 seconds
      setTimeout(() => {
        setEmailStatus(prev => ({ ...prev, message: '' }));
      }, 3000);

    } catch (error) {
      setEmailStatus({
        isSending: false,
        message: '',
        error: `Email failed: ${error.message}`
      });
    }
  };

  const avatarColors = [
    '#6366f1', '#8b5cf6', '#06b6d4', '#10b981',
    '#f59e0b', '#ef4444', '#ec4899', '#84cc16'
  ];

  const fontOptions = [
    { value: 'Inter', label: 'Inter' },
    { value: 'Poppins', label: 'Poppins' },
    { value: 'SF Mono', label: 'SF Mono' },
    { value: 'JetBrains Mono', label: 'JetBrains Mono' }
  ];

  const exportFormats = [
    { value: 'pdf', label: 'PDF (.pdf)' },
    { value: 'docx', label: 'Word (.docx)' },
    { value: 'txt', label: 'Text (.txt)' },
    { value: 'html', label: 'HTML (.html)' }
  ];

  return (
    <div className={`min-h-screen transition-colors duration-300 ${
      isDark 
        ? 'bg-gradient-to-br from-gray-900 via-slate-800 to-gray-900' 
        : 'bg-gradient-to-br from-indigo-50 via-white to-violet-50'
    }`}>
      {/* Header */}
      <div className={`border-b transition-colors duration-300 ${
        isDark ? 'border-gray-700 bg-gray-800/50' : 'border-gray-200 bg-white/50'
      } backdrop-blur-sm`}>
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-4">
              <Button 
                variant="ghost" 
                size="sm" 
                className="p-2"
                onClick={handleGoBack} // Add the onClick handler
              >
                <ArrowLeft className="w-5 h-5" />
              </Button>
              <div className="flex items-center space-x-3">
                <div className={`p-2 rounded-xl ${
                  isDark ? 'bg-indigo-600' : 'bg-indigo-100'
                }`}>
                  <SettingsIcon className={`w-5 h-5 ${
                    isDark ? 'text-white' : 'text-indigo-600'
                  }`} />
                </div>
                <div>
                  <h1 className={`text-xl font-semibold ${
                    isDark ? 'text-white' : 'text-gray-900'
                  }`}>
                    Settings
                  </h1>
                  <p className={`text-sm ${
                    isDark ? 'text-gray-400' : 'text-gray-500'
                  }`}>
                    Customize your workspace
                  </p>
                </div>
              </div>
            </div>
            <Button 
              onClick={handleSave}
              disabled={!hasChanges}
              className={`${hasChanges ? 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700' : ''}`}
            >
              <Save className="w-4 h-4 mr-2" />
              Save Changes
            </Button>
          </div>
        </div>
      </div>

      {/* Save Notification */}
      {showSaveNotification && (
        <div className="fixed top-4 right-4 z-50 animate-in slide-in-from-top-2 fade-in duration-300">
          <div className={`flex items-center px-4 py-3 rounded-2xl shadow-lg ${
            isDark 
              ? 'bg-green-900 border border-green-800 text-green-100' 
              : 'bg-green-50 border border-green-200 text-green-800'
          }`}>
            <Check className="w-5 h-5 mr-2" />
            Settings saved successfully!
          </div>
        </div>
      )}

      {/* Settings Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid gap-8 lg:grid-cols-2">
          
          {/* Profile Management */}
          <SettingsCard
            icon={User}
            title="Profile"
            description="Manage your profile and cursor appearance"
            isDark={isDark}
          >
            <div className="space-y-6">
              <div>
                <label className={`block text-sm font-medium mb-2 ${
                  isDark ? 'text-gray-300' : 'text-gray-700'
                }`}>
                  Display Name
                </label>
                <input
                  type="text"
                  value={settings.profile.name}
                  onChange={(e) => updateSetting('profile', 'name', e.target.value)}
                  className={`w-full px-4 py-3 rounded-xl border transition-colors duration-200 ${
                    isDark 
                      ? 'bg-gray-700 border-gray-600 text-white placeholder-gray-400 focus:border-indigo-500' 
                      : 'bg-white border-gray-200 text-gray-900 placeholder-gray-500 focus:border-indigo-500'
                  } focus:outline-none focus:ring-2 focus:ring-indigo-500/20`}
                  placeholder="Enter your name"
                />
              </div>

              <div>
                <label className={`block text-sm font-medium mb-2 ${
                  isDark ? 'text-gray-300' : 'text-gray-700'
                }`}>
                  Cursor Color
                </label>
                <div className="flex items-center space-x-3">
                  <div 
                    className="w-10 h-10 rounded-xl border-2 border-white shadow-lg"
                    style={{ backgroundColor: settings.profile.avatarColor }}
                  />
                  <ColorPicker
                    colors={avatarColors}
                    selected={settings.profile.avatarColor}
                    onChange={(color) => updateSetting('profile', 'avatarColor', color)}
                    isDark={isDark}
                  />
                </div>
              </div>
            </div>
          </SettingsCard>

          {/* Theme Settings */}
          <SettingsCard
            icon={Palette}
            title="Appearance"
            description="Customize the look and feel"
            isDark={isDark}
          >
            <div className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <label className={`block text-sm font-medium ${
                    isDark ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    Theme Mode
                  </label>
                  <p className={`text-sm mt-1 ${
                    isDark ? 'text-gray-400' : 'text-gray-500'
                  }`}>
                    Choose your preferred theme
                  </p>
                </div>
                <div className="flex items-center space-x-2">
                  <Sun className={`w-5 h-5 ${
                    !isDark ? 'text-yellow-500' : 'text-gray-400'
                  }`} />
                  <Toggle
                    checked={isDark}
                    onChange={toggleTheme}
                  />
                  <Moon className={`w-5 h-5 ${
                    isDark ? 'text-indigo-400' : 'text-gray-400'
                  }`} />
                </div>
              </div>

              <div className={`p-4 rounded-xl ${
                isDark ? 'bg-gray-700' : 'bg-gray-50'
              }`}>
                <div className="flex items-center space-x-2 mb-2">
                  <Monitor className={`w-4 h-4 ${
                    isDark ? 'text-gray-400' : 'text-gray-600'
                  }`} />
                  <span className={`text-sm font-medium ${
                    isDark ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    System Integration
                  </span>
                </div>
                <p className={`text-sm ${
                  isDark ? 'text-gray-400' : 'text-gray-600'
                }`}>
                  Theme will automatically switch based on your system preferences
                </p>
              </div>
            </div>
          </SettingsCard>

          {/* Editor Preferences */}
          <SettingsCard
            icon={Type}
            title="Editor"
            description="Customize your editing experience"
            isDark={isDark}
            className="lg:col-span-2"
          >
            <div className="grid gap-6 md:grid-cols-2">
              <div className="space-y-6">
                <div>
                  <label className={`block text-sm font-medium mb-2 ${
                    isDark ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    Font Family
                  </label>
                  <Select
                    value={settings.editor.fontFamily}
                    onChange={(value) => updateSetting('editor', 'fontFamily', value)}
                    options={fontOptions}
                    isDark={isDark}
                  />
                </div>

                <div>
                  <label className={`block text-sm font-medium mb-2 ${
                    isDark ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    Font Size: {settings.editor.fontSize}px
                  </label>
                  <Slider
                    value={settings.editor.fontSize}
                    onChange={(value) => updateSetting('editor', 'fontSize', value)}
                    min={12}
                    max={24}
                    step={1}
                    isDark={isDark}
                  />
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <label className={`block text-sm font-medium mb-2 ${
                    isDark ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    Line Height: {settings.editor.lineHeight}
                  </label>
                  <Slider
                    value={settings.editor.lineHeight}
                    onChange={(value) => updateSetting('editor', 'lineHeight', value)}
                    min={1.0}
                    max={2.0}
                    step={0.1}
                    isDark={isDark}
                  />
                </div>

                <div className={`p-4 rounded-xl border ${
                  isDark ? 'bg-gray-700 border-gray-600' : 'bg-gray-50 border-gray-200'
                }`}>
                  <h4 className={`font-medium mb-2 ${
                    isDark ? 'text-white' : 'text-gray-900'
                  }`} style={{ 
                    fontFamily: settings.editor.fontFamily,
                    fontSize: `${settings.editor.fontSize}px`,
                    lineHeight: settings.editor.lineHeight
                  }}>
                    Preview Text
                  </h4>
                  <p className={`${
                    isDark ? 'text-gray-300' : 'text-gray-600'
                  }`} style={{ 
                    fontFamily: settings.editor.fontFamily,
                    fontSize: `${settings.editor.fontSize}px`,
                    lineHeight: settings.editor.lineHeight
                  }}>
                    This is how your text will appear in the editor with the current settings.
                  </p>
                </div>
              </div>
            </div>
          </SettingsCard>

          {/* Export Options */}
          <SettingsCard
            icon={FileText}
            title="Export"
            description="Configure document export settings"
            isDark={isDark}
            className="lg:col-span-2"
          >
            <div className="grid gap-6 md:grid-cols-2">
              <div className="space-y-6">
                <div>
                  <label className={`block text-sm font-medium mb-2 ${
                    isDark ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    Default Export Format
                  </label>
                  <Select
                    value={settings.export.defaultFormat}
                    onChange={(value) => updateSetting('export', 'defaultFormat', value)}
                    options={exportFormats}
                    isDark={isDark}
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <label className={`block text-sm font-medium ${
                      isDark ? 'text-gray-300' : 'text-gray-700'
                    }`}>
                      Include Metadata
                    </label>
                    <p className={`text-sm mt-1 ${
                      isDark ? 'text-gray-400' : 'text-gray-500'
                    }`}>
                      Add creation date, author info
                    </p>
                  </div>
                  <Toggle
                    checked={settings.export.includeMetadata}
                    onChange={(checked) => updateSetting('export', 'includeMetadata', checked)}
                  />
                </div>
              </div>

              <div className="space-y-4">
                <h4 className={`font-medium ${
                  isDark ? 'text-white' : 'text-gray-900'
                }`}>
                  Quick Export Actions
                </h4>
                
                {/* Status Messages */}
                {(exportStatus.message || exportStatus.error) && (
                  <div className={`p-3 rounded-lg text-sm ${
                    exportStatus.error 
                      ? 'bg-red-100 border border-red-200 text-red-700 dark:bg-red-900/20 dark:border-red-800 dark:text-red-400'
                      : 'bg-green-100 border border-green-200 text-green-700 dark:bg-green-900/20 dark:border-green-800 dark:text-green-400'
                  }`}>
                    {exportStatus.error || exportStatus.message}
                  </div>
                )}

                <div className="grid gap-2">
                  {exportFormats.map((format) => (
                    <Button
                      key={format.value}
                      variant="outline"
                      onClick={() => handleExport(format.value)}
                      disabled={exportStatus.isExporting}
                      className={`justify-start ${
                        isDark 
                          ? 'border-gray-600 hover:bg-gray-700 text-gray-300' 
                          : 'border-gray-200 hover:bg-gray-50 text-gray-700'
                      } ${exportStatus.isExporting ? 'opacity-50 cursor-not-allowed' : ''}`}
                    >
                      <Download className="w-4 h-4 mr-2" />
                      {exportStatus.isExporting ? 'Exporting...' : `Export as ${format.label}`}
                    </Button>
                  ))}
                </div>

                {/* Email Export Option */}
                <div className="mt-4 p-4 rounded-lg border border-dashed border-gray-300 dark:border-gray-600">
                  <h5 className={`font-medium mb-2 ${
                    isDark ? 'text-white' : 'text-gray-900'
                  }`}>
                    Email Export
                  </h5>
                  <p className={`text-sm mb-3 ${
                    isDark ? 'text-gray-400' : 'text-gray-600'
                  }`}>
                    Send exported document to your email
                  </p>
                  
                  {(emailStatus.message || emailStatus.error) && (
                    <div className={`p-2 rounded text-xs mb-2 ${
                      emailStatus.error 
                        ? 'bg-red-100 border border-red-200 text-red-700 dark:bg-red-900/20 dark:border-red-800 dark:text-red-400'
                        : 'bg-green-100 border border-green-200 text-green-700 dark:bg-green-900/20 dark:border-green-800 dark:text-green-400'
                    }`}>
                      {emailStatus.error || emailStatus.message}
                    </div>
                  )}

                  <Button
                    variant="outline"
                    onClick={() => handleSendEmail('data-export')}
                    disabled={emailStatus.isSending}
                    className={`w-full justify-start ${
                      isDark 
                        ? 'border-gray-600 hover:bg-gray-700 text-gray-300' 
                        : 'border-gray-200 hover:bg-gray-50 text-gray-700'
                    } ${emailStatus.isSending ? 'opacity-50 cursor-not-allowed' : ''}`}
                  >
                    <Mail className="w-4 h-4 mr-2" />
                    {emailStatus.isSending ? 'Sending...' : 'Send to Email'}
                  </Button>
                </div>
              </div>
            </div>
          </SettingsCard>

        </div>
      </div>
    </div>
  );
};

export default SettingsPage;
